version: "3.9"
services:
  mongo:
    container_name: codearena-mongo
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: codearena
    ports:
      - "${MONGO_BIND_HOST:-127.0.0.1}:${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  mongo-express:
    container_name: codearena-mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_BIND_HOST:-127.0.0.1}:${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - backend-network

  api:
    container_name: codearena-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "${API_BIND_HOST:-127.0.0.1}:${API_PORT:-3000}:3000"
    depends_on:
      - mongo
    networks:
      - backend-network

  web:
    container_name: codearena-web
    build: ./web
    ports:
      - "${WEB_BIND_HOST:-0.0.0.0}:${WEB_PORT:-5173}:5173"
    depends_on:
      - api
    networks:
      - backend-network

volumes:
  mongo_data:

networks:
  backend-network:
    driver: bridge
