version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: codearena
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend-network

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - backend-network

volumes:
  mongo_data:

networks:
  backend-network:
    driver: bridge
