version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    ports: ["3000:3000"]
    depends_on:
      - mongo

  web:
    build: ./web
    ports: ["5173:5173"]
    depends_on:
      - api

volumes:
  mongo_data:
